### PR TITLE
Fix ingredients being cached too early. Close #1510

### LINKED ISSUE #1510: Crafttweaker and Immersive engineering incompatibility when it comes to recipe removal functions
### Issue description

On a worlds first load in a session, IE recipes are broken, there seems to be some issue where IE isn't able to determine the contents of tags because of something to do with an item removal script, resulting in IE recipes that use tags to determine their outputs just outputting nothing at all.

This issue lasts until a reload, and then is fixed, but stops working again after the game is restarted.

Pre-reload:

Post-reload:

### Steps to reproduce

Load Crafttweaker, JEITweaker, Immersive engineering, and JEI in the same profile together.

Add the script provided into the scripts folder.

Launch the game.

Launch a new world.

The bug can be observed, and will correct itself after a reload, but will return after the game fully restarts and the world is entered again for the first time.

### Script used

https://gist.github.com/Warhand/7bbe1340eb9138109cb48b326a269d48

### The crafttweaker.log file

https://gist.github.com/Warhand/23f010da77b2bd1087f9e61d39772fe7

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.1.25

### CraftTweaker version

9.1.155

### Other relevant information

Immersive engineering version: 8.0.2-149
JEI: 9.5.5.174

### The latest.log file

https://gist.github.com/Warhand/291e8a6457fcf9e6f23ea85359a4b94d

### PR DESCRIPTION
**Pull request by jaredlll08**
The basics of what is going on:

1) At the start of the CRT reload, set a boolean to true
2) If an Ingredient is dissolved while that boolean is true, add it to a list
3) When `TagValue#getItems` is called while that boolean is true, query the `TagManager` directly (which has already loaded tags, but has not been saved to the registry)
4) At the end of the CRT reload, set the boolean to false, loop through the list of ingredients that was made in 2 and set `Ingredient#itemStacks` to null (as if it was never dissolved to begin with), clear the list

### CODE REVIEW

File: Common/src/main/java/com/blamejared/crafttweaker/mixin/common/transform/item/MixinIngredientTagValue.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+                    .accessibleResources()
+                    .crafttweaker$getTagManager().getResult().stream()
+                    .filter(loadResult -> loadResult.key().equals(Registry.ITEM_REGISTRY))
+                    .map(GenericUtil::<TagManager.LoadResult<Item>>uncheck)
+                    .flatMap(loadResult -> loadResult.tags()
+                            .getOrDefault(this.tag.location(), new Tag<>(List.of()))
+                            .getValues()
+                            .stream()
+                            .map(Holder::value)
+                            .map(ItemStack::new)).toList());
```
Comment (TheSilkMiner) [inline Common/src/main/java/com/blamejared/crafttweaker/mixin/common/transform/item/MixinIngredientTagValue.java]: Wouldn't this be better to result in a series of maps rather than nesting the flatmap? Or is this better for performance?

File: Common/src/main/java/com/blamejared/crafttweaker/api/ingredient/IngredientCacheBuster.java [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * Used to bust the {@link Ingredient}#itemStacks cache when the {@link Ingredient} was resolved during a Server reload (When an instance of {@link net.minecraft.tags.TagManager} is available.
+ */
+public class IngredientCacheBuster {
+    
+    private static boolean claimed;
```
Comment (TheSilkMiner) [inline Common/src/main/java/com/blamejared/crafttweaker/api/ingredient/IngredientCacheBuster.java:15]: No thread safety: yay or nay? Maybe if we'd need it, what about a thread local instance?

Comment (jaredlll08) [reply Common/src/main/java/com/blamejared/crafttweaker/api/ingredient/IngredientCacheBuster.java:15]: I don't think we need it, the class will be moved to `impl` instead of `api`.

If anyone needs to use the class for their own script load, please get in contact with us and we can see what we can do.
